language: c

dist: xenial

addons:
  apt:
    packages:
      - astyle
      - python-pip
      - gcc-multilib

before_install:
  # FYI: known good with HEAD at 8551fc60fc515cd290ba38ee8c758c1f4df52b56
  - git clone https://github.com/perltidy/perltidy.git perltidy
  - |
    (cd perltidy &&
     perl Makefile.PL &&
     make &&
     sudo make install)

install:
  - sudo pip install yapf

script:
  - tools/check-syntax -f && git diff --exit-code
  - make
